spring.config.activate.on-profile: local

spring:
  datasource:
    hikari:
      maximum-pool-size: 10

  db:
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    jdbc-url: jdbc:tibero:thin:@localhost:8629:tibero
    username: tibero
    password: tibero

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

  flyway:
    locations: classpath:/db/migration
    sql-migration-suffixes: sql
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: TIBERO
    enabled: true
